/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Combustivel;
import controller.VeiculoController;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Thiago
 */
public class CadVeic extends javax.swing.JInternalFrame {

    private VeiculoController veiculoController;

    /**
     * Creates new form TelaCadastro
     */
    public CadVeic() throws IOException {
        initComponents();
        veiculoController = new VeiculoController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbDiesel = new javax.swing.JRadioButton();
        rbEtanol = new javax.swing.JRadioButton();
        rbGasolina = new javax.swing.JRadioButton();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        btnCadVeic = new javax.swing.JButton();
        btnResetVeic = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);

        jLabel1.setText("Marca");

        jLabel2.setText("Modelo");

        jLabel3.setText("Ano");

        buttonGroup2.add(rbDiesel);
        rbDiesel.setText("Diesel");

        buttonGroup2.add(rbEtanol);
        rbEtanol.setText("Etanol");

        buttonGroup2.add(rbGasolina);
        rbGasolina.setText("Gasolina");

        btnCadVeic.setText("Cadastrar");
        btnCadVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadVeicActionPerformed(evt);
            }
        });

        btnResetVeic.setText("Reset");
        btnResetVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetVeicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtModelo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtMarca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAno, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbDiesel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbEtanol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbGasolina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCadVeic, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnResetVeic, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDiesel)
                    .addComponent(rbEtanol)
                    .addComponent(rbGasolina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadVeic)
                    .addComponent(btnResetVeic))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadVeicActionPerformed
        try {
            String marca = txtMarca.getText();
            String modelo = txtModelo.getText();
            int ano = Integer.parseInt(txtAno.getText());
            Combustivel combustivel = null;

            if (rbGasolina.isSelected()) {
                combustivel = Combustivel.GASOLINA;
            } else if (rbDiesel.isSelected()) {
                combustivel = Combustivel.DIESEL;
            } else if (rbEtanol.isSelected()) {
                combustivel = Combustivel.ETANOL;
            }

            if (combustivel != null) {
                veiculoController.salvarVeiculo(marca, modelo, ano, combustivel);
                JOptionPane.showMessageDialog(this, "Veículo cadastrado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um tipo de combustível.");
            }

            txtMarca.setText("");
            txtModelo.setText("");
            txtAno.setText("");
            buttonGroup2.clearSelection();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ano inválido.");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar o veículo.");
        }
    }//GEN-LAST:event_btnCadVeicActionPerformed

    private void btnResetVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetVeicActionPerformed
        txtMarca.setText(null);
        txtModelo.setText(null);
        txtAno.setText(null);
        buttonGroup2.clearSelection();
    }//GEN-LAST:event_btnResetVeicActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadVeic;
    private javax.swing.JButton btnResetVeic;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rbDiesel;
    private javax.swing.JRadioButton rbEtanol;
    private javax.swing.JRadioButton rbGasolina;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
}
